### PR TITLE
quicksetup.sh

### PR DESCRIPTION
**Pull request by Vincent392**
A Quick Setup file for idiots (Also saves time tracking down packages for developers)

### CODE REVIEW

**Comment by vulkxn** [comment]
Maybe a markdown document would better fit this purpose as this would only work on Debian based linux distros

**Comment by vulkxn** [comment]
To be honest a script is probably more effort than a markdown document describing how it should be done

**Comment by Vincent392** [comment]
still, could be worse.

**Comment by 5GameMaker** [comment]
I think a better README and some docs would do a bit better job 🤷🏻

**Comment by Vincent392** [comment]
Hmm.
HMMM.
Knowing shellscript is quite similar to batchscript I could probably do that,
Or the docs method.

**Comment by Vincent392** [comment]
Who knows.

**Comment by vulkxn** [comment]
Just make a section in the README.md file called Building Prerequisites and name the packages that need to be on the system. Everyone should know what package manager the distro they use.

**Comment by KapPetrov** [comment]
Yeah, a section in README.md will be better than a .sh file.

**Comment by Vincent392** [comment]
I'm going to close this. update the README.md and add the celOS code.

**Pull request closed without merging**
